---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    pod: hello-world-pod
  ports:
    - protocol: TCP
      port: 8080 # The port, the service listens on.
      targetPort: 80 # The port, the traffic is sent to on the Pod.
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      pod: hello-world-pod
  template:
    metadata:
      labels:
        pod: hello-world-pod
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world
